version: "3.8"
volumes:
  mysqldata:
  ollama_data:
  anythingllm_data:

networks:
  default:
    driver: bridge

services:
  phpfpm:
    build:
      context: Docker/php-fpm
    container_name: php-fpm
    environment:
      TERM: xterm-color
      DATABASE_DSN: mysql:dbname=myhelpdesk;host=mysql
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      MISTRAL_API_KEY: ${MISTRAL_API_KEY:-}
      JWT_SECRET: ${JWT_SECRET:-}
    cap_add:
      - SYS_PTRACE
    volumes:
      - type: "bind"
        source: "./app/"
        target: "/project"
      - type: "bind"
        source: "../"
        target: "/workspace"
    networks:
      - default

  nginx:
    build:
      context: Docker/nginx
    container_name: nginx
    ports:
      - 8084:80
    environment:
      TERM: xterm-color
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "my-app.local"
    cap_add:
      - SYS_PTRACE
    volumes:
      - type: bind
        source: "./app/"
        target: "/project"
      - type: bind
        source: "../"
        target: "/workspace"
      - type: bind
        source: "./docker/nginx/nginx.conf"
        target: "/etc/nginx/nginx.conf"
      - type: bind
        source: "./docker/nginx/phpfpm.conf"
        target: "/etc/nginx/conf.d/phpfpm.conf"
      - type: bind
        source: "./docker/nginx/default.conf"
        target: "/etc/nginx/conf.d/default.conf"
    depends_on:
      - phpfpm
    networks:
      - default

  mysql:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myhelpdesk
      MYSQL_HOST: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3308:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8094:80'
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: database
      PMA_USER: 'root'
      PMA_PASSWORD: 'password'
    networks:
      - default


  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
      - "3001:3001"
    volumes:
      - ./storage:/app/server/storage
    environment:
      - STORAGE_DIR=/app/server/storage
      - LLM_BACKEND_URL={LLM_BACKEND_URL:-}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
      - JWT_SECRET=${JWT_SECRET:-}
    restart: always
    cap_add:
      - SYS_ADMIN

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - default
    command: ""
